WebApplication1/Controllers/SachonlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WebApplication1.Models;
namespace TranPhamThanhTrung.SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {

        SachOnlineEntities data = new SachOnlineEntities();

        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }

        private List<SACH> LaySachBanNhieu(int count)
        {
            // Sort by SoLuongBan (Sold Number) descending and take the top 6
            return data.SACHes.OrderByDescending(s => s.SoLuongBan).Take(count).ToList();
        }

        public ActionResult ChuDePartial()
        {
            var listChuDe = from cd in data.CHUDEs select cd;
            return PartialView(listChuDe);
        }

        // GET: SachOnline
        public ActionResult Index()
        {
            var listSachMoi = LaySachMoi(6); // Lấy 6 quyển sách mới nhất
            return View(listSachMoi);
        }

        public ActionResult NavPartial()
        {
            return PartialView();
        }

        public ActionResult SliderPartial()
        {
            return PartialView();
        }

        public ActionResult NhaXuatBanPartial()
        {
            var listNhaXuatBan = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(listNhaXuatBan);
        }

        public ActionResult SachBanNhieuPartial()
        {
            var sachBanNhieu = LaySachBanNhieu(6);
            return PartialView(sachBanNhieu);
        }

        public ActionResult FooterPartial()
        {
            return PartialView();
        }
    }
}

WebApplication1/Views/SachOnline/ChuDePartial.cshtml
@model IEnumerable<WebApplication1.Models.CHUDE>
<ul class="list-group">
    <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO CHỦ ĐỀ</li>
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SachTheoChuDe", "SachOnline", new { id = item.MaCD })"
           class="list-group-item">@item.TenChuDe</a>
    }
</ul>

WebApplication1/Views/SachOnline/FooterPartial.cshtml
<footer class="container well" style="text-align: center;">
    <p>©@DateTime.Now.Year - Nhà sách ABC. Allright Reserved</p>
    <p>Website được phát triển để sử dụng làm bài tập thực hành môn Lập trình Web</p>
    <p>Email: abc@gmail.com</p>
</footer>

WebApplication1/Views/SachOnline/Index.cshtml
@model IEnumerable<WebApplication1.Models.SACH>

@{
    ViewBag.Title = "TRANG CHỦ";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<style type="text/css">
    .imgbook {
        transition: all 1s ease-in;
        width: 400px;
    }

    .imgbook:hover {
        transform: scale(0.9);
        cursor: pointer;
    }
</style>

<h2 class="text-center">SÁCH MỚI</h2>
<hr />
<div class="row text-center">
    @foreach(var sach in Model) { 
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <div class="thumbnail">
                <img src="~/Images/@sach.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook" style="width: 400px"/>
                <div class="caption">
                    <h4 style="min-height: 70px">
                        <a href="@Url.Action("BookDetail", "SachOnline", new {
                            id = sach.MaSach    
                        })">@sach.TenSach</a>
                    </h4>
                    <p>
                        <a href="#" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Add to cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
<nav class="text-center">
    <ul class="pagination">
        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="active">
            <a href="#">1</a>
        </li>
        <li class="active">
            <a href="#">2</a>
        </li>
        <li class="active">
            <a href="#">3</a>
        </li>
        <li class="active">
            <a href="#">4</a>
        </li>
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

WebApplication1/Views/SachOnline/NavPartial.cshtml
<nav class="navbar navbar-inverse">
    <!--navbar-fixed-top-->
    <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">SachOnline</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar1">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="#">TRANG CHỦ</a>
                </li>
                <li>
                    <a href="#">GIỚI THIỆU</a>
                </li>
                <li>
                    <a href="#">LIÊN HỆ</a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">Người dùng<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><span class="glyphicon glyphicon-user"></span> Đăng ký</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#"><span class="glyphicon glyphicon-log-in"></span> Đăng nhập</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Giỏ hàng (0)</a>
                </li>
            </ul>

            <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm">
                </div>
                <button type="submit" class="btn btn-default">Tìm</button>
            </form>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-->
</nav>

WebApplication1/Views/SachOnline/NhaXuatBanPartial.cshtml
@model IEnumerable<WebApplication1.Models.NHAXUATBAN>
<ul class="list-group">
    <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO CHỦ ĐỀ</li>
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SachTheoChuDe", "SachOnline", new { id = item.MaNXB })"
           class="list-group-item">@item.TenNXB</a>
    }
</ul>

WebApplication1/Views/SachOnline/SachBanNhieuPartial.cshtml
@model IEnumerable<WebApplication1.Models.SACH>

@{
    var list = Model.ToList();
}

<h2 class="text-center">SÁCH BÁN NHIỀU</h2>
<div class="row">
    @* Left Column: Items 1, 3, 5 (Index 0, 2, 4) *@
    <div class="col-lg-6 col-md-6">
        <div class="media-object-default">
            @for (int i = 0; i < list.Count; i++)
            {
                if (i % 2 == 0) // Even index for left column
                {
                    <div class="media" style="min-height: 160px;">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object imgsachbannhieu"
                                     src="@Url.Content("~/Images/" + list[i].AnhBia)"
                                     alt="@list[i].TenSach"
                                     style="width: 100px; height: 150px; object-fit: cover; display: block;">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">@list[i].TenSach</h4>
                            @(list[i].MoTa.Length > 150 ? list[i].MoTa.Substring(0, 150) + "..." : list[i].MoTa)
                            <p><strong>Giá: @String.Format("{0:0,0}", list[i].GiaBan) VNĐ</strong></p>
                        </div>
                    </div>
                }
            }
        </div>
    </div>

    @* Right Column: Items 2, 4, 6 (Index 1, 3, 5) *@
    <div class="col-lg-6 col-md-6">
        <div class="media-object-default">
            @for (int i = 0; i < list.Count; i++)
            {
                if (i % 2 != 0) // Odd index for right column
                {
                    <div class="media" style="min-height: 160px;">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object imgsachbannhieu"
                                     src="@Url.Content("~/Images/" + list[i].AnhBia)"
                                     alt="@list[i].TenSach"
                                     style="width: 100px; height: 150px; object-fit: cover; display: block;">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">@list[i].TenSach</h4>
                            @(list[i].MoTa.Length > 150 ? list[i].MoTa.Substring(0, 150) + "..." : list[i].MoTa)
                            <p><strong>Giá: @String.Format("{0:0,0}", list[i].GiaBan) VNĐ</strong></p>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>
<hr>

WebApplication1/Views/SachOnline/SliderPartial.cshtml
<div id="carousel1" class="carousel slide">
    <ol class="carousel-indicators">
        <li data-target="#carousel1" data-slide-to="0" class="active"> </li>
        <li data-target="#carousel1" data-slide-to="1" class=""> </li>
        <li data-target="#carousel1" data-slide-to="2" class=""> </li>
        <li data-target="#carousel1" data-slide-to="3" class=""> </li>
        <li data-target="#carousel1" data-slide-to="4" class=""> </li>
        <li data-target="#carousel1" data-slide-to="5" class=""> </li>
    </ol>
    <div class="carousel-inner">

        <div class="item active">
            <img class="img-responsive" src="~/Images/Slider/01.jpg" alt="thumb">
            <div class="carousel-caption"> Quảng cáo 1 </div>
        </div>
        <div class="item">
            <img class="img-responsive" src="~/Images/Slider/02.jpg" alt="thumb">
            <div class="carousel-caption"> Quảng cáo 2 </div>
        </div>
        <div class="item">
            <img class="img-responsive" src="~/Images/Slider/03.jpg" alt="thumb">
            <div class="carousel-caption"> Quảng cáo 3 </div>
        </div>
        <div class="item">
            <img class="img-responsive" src="~/Images/Slider/04.jpg" alt="thumb">
            <div class="carousel-caption"> Quảng cáo 4 </div>
        </div>
        <div class="item">
            <img class="img-responsive" src="~/Images/Slider/05.jpg" alt="thumb">
            <div class="carousel-caption"> Quảng cáo 5 </div>
        </div>
        <div class="item">
            <img class="img-responsive" src="~/Images/Slider/06.jpg" alt="thumb">
            <div class="carousel-caption"> Quảng cáo 6 </div>
        </div>
    </div>
    <a class="left carousel-control" href="#carousel1" data-slide="prev"><span class="icon-prev"></span></a>
    <a class="right carousel-control" href="#carousel1" data-slide="next"><span class="icon-next"></span></a>
</div>